version: "3"
services:
  mmgis:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - 8888:8888
    restart: on-failure
    volumes:
      - ./Missions:/usr/src/app/Missions
  db:
    image: postgis/postgis:10-2.5-alpine
    env_file: .env
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - mmgis-db:/var/lib/postgresql/data
volumes:
  mmgis-db:
